name: cached_s5_video_example
description: "A test app for cached s5 video."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  cached_s5_video:
    path: ../
  s5: ^0.2.0
  hive: ^2.2.3
  logger: ^2.4.0
  cached_s5_manager: ^1.2.1
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
